Allow user to corrupt vendor image for avb test
add new choice for vendor.img to let user choose
the vendor.img to be corrupted in order to meet
treble requirements

Change-Id: Iced935fa7c68c617edbf469891e17740d7a305b7
Tracked-On: OAM-52309
Signed-off-by: dengx2x <xiangx.deng@intel.com>
Reviewed-on: 607407

diff --git a/test/avb_test_prepare b/test/avb_test_prepare
--- a/test/avb_test_prepare
+++ b/test/avb_test_prepare
@@ -22,10 +22,11 @@ USERKEY="$KEYS_DIR/userkey"
 WD=`pwd`
 
 function usage {
-    echo "usage: `basename $0` [-b <boot_or_recovery_image_path> | -s <system_image_path> | -c | -h]"
+    echo "usage: `basename $0` [-b <boot_or_recovery_image_path> | -s <system_image_path> | -v <vendor_image_path> | -c | -h]"
     echo "       -c: clean everything"
     echo "       -b <image_path>: name of the boot/recovery image to split/sign"
     echo "       -s <image_path>: name of the system image to corrupt"
+    echo "       -v <image_path>: name of the vendor image to corrupt"
     echo "       -h: print this message"
     echo "example:"
     echo "        $0 -b ~/boot.img"
@@ -156,6 +157,111 @@ function generate_corrupted_system_images {
     sed -i 's/SurfaceFlinger died/FlingerSurface died/' $IMG_DIR/system_corrupted_block.img
 }
 
+function generate_corrupted_vendor_images {
+    LIST_VBMETA_IMGS=("verity.img" "vendor_metadata.img")
+    START_OFFSET=()
+    TMP_VBMETA_IMG="$TMP_DIR/tmp.img"
+
+    # for vendor.img
+    read fec_size <<< "$($AVB_TOOL info_image --image $TMP_DIR/$IMG.img | grep 'FEC size:' | awk -F" " '{print $3}')"
+
+    # for vbmeta.img
+    read authen_blksize <<< "$($AVB_TOOL info_image --image $TMP_DIR/vbmeta.img | grep 'Authentication Block:' | awk -F" " '{print $3}')"
+    read auxil_blksize <<< "$($AVB_TOOL info_image --image $TMP_DIR/vbmeta.img | grep 'Auxiliary Block:' | awk -F" " '{print $3}')"
+
+    authen_offset=256
+    hash_offset=$authen_offset
+    sign_offset=`expr $authen_offset + 32`
+    sign_size=512
+    auxil_offset=`expr $authen_offset + $authen_blksize`
+    descr_offset=$auxil_offset
+    # echo "authen_offset : $authen_offset , hash_offset : $hash_offset , sign_offset : $sign_offset , auxil_offset : $auxil_offset , descr_offset : $descr_offset "
+
+    if [ $fec_size -ne 0 ]
+    then
+       fec_supported=1
+       read tree_offset tree_len <<< "$($SIMG_DUMP -v $TMP_DIR/$IMG.img | tail -6  | head -1 | awk '{print $2" "$3}')"
+       read fec_offset fec_size <<< "$($SIMG_DUMP -v $TMP_DIR/$IMG.img | tail -5  | head -1 | awk '{print $2" "$3}')"
+       # echo "fec_offset = $fec_offset, fec_size = $fec_size"
+    else
+       fec_supported=0
+       read tree_offset tree_len <<< "$($SIMG_DUMP -v $TMP_DIR/$IMG.img | tail -5  | head -1 | awk '{print $2" "$3}')"
+       fec_offset=0
+    fi
+
+    # echo "tree offset : $tree_offset , tree len : $tree_len "
+
+    if [ $fec_supported -eq 1 ]
+    then
+        dd if=$TMP_DIR/$IMG.img of=$TMP_VBMETA_IMG bs=$tree_offset skip=1 2>/dev/null
+        dd if=$TMP_VBMETA_IMG of=$TMP_DIR/${LIST_VBMETA_IMGS[0]} bs=$tree_len count=1 2>/dev/null
+        START_OFFSET[0]=$tree_offset
+    else
+        i=0
+        while read start length; do
+            # use of tmp file but save us some unreliable arithmetic
+            dd if=$TMP_DIR/$IMG.img of=$TMP_VBMETA_IMG bs=$start skip=1 2>/dev/null
+            dd if=$TMP_VBMETA_IMG of=$TMP_DIR/${LIST_VBMETA_IMGS[$i]} bs=$length count=1 2>/dev/null
+            START_OFFSET[$i]=$start
+            # echo "fec_supported = 0 ,start = $start, length = $length"
+        done <<< "$($SIMG_DUMP -v $TMP_DIR/$IMG.img | tail -5  | head -1 | awk '{print $2" "$3}')"
+    fi
+
+    # ready for vbmeta's corrupt...
+    dd if=$TMP_DIR/vbmeta.img of=$TMP_VBMETA_IMG bs=$sign_offset skip=1 2>/dev/null
+    dd if=$TMP_VBMETA_IMG of=$TMP_DIR/${LIST_VBMETA_IMGS[1]} bs=$sign_size count=1 2>/dev/null
+    START_OFFSET[1]=$sign_offset
+
+    for i in "${!LIST_VBMETA_IMGS[@]}"
+    do
+        # make a copy to keep originals
+        cp $TMP_DIR/${LIST_VBMETA_IMGS[$i]} $TMP_DIR/corrupted_${LIST_VBMETA_IMGS[$i]}
+        if [ "${LIST_VBMETA_IMGS[$i]}" = "vendor_metadata.img" ]
+        then
+            # for vbmeta.img
+            # skip 256 + 32 first bytes to corrupt signature data
+            # and introduce some random bytes
+            bs=1
+            count=20
+            seek=$sign_offset
+        else
+            # by default corrupt the first block
+            bs=4096
+            count=1
+            seek=0
+        fi
+
+        echo "Corrupting ${LIST_VBMETA_IMGS[$i]}..."
+        dd if=/dev/urandom bs=$bs count=$count conv=notrunc seek=$seek of=$TMP_DIR/corrupted_${LIST_VBMETA_IMGS[$i]}
+
+        if [ "${LIST_VBMETA_IMGS[$i]}" = "vendor_metadata.img" ]
+        then
+           # create vbmeta_corrupted_vendor_verity.img for vbmeta.img
+           echo "Creating vbmeta_corrupted_${LIST_VBMETA_IMGS[$i]}..."
+           cp $TMP_DIR/vbmeta.img $IMG_DIR/vbmeta_corrupted_${LIST_VBMETA_IMGS[$i]}
+           # echo "for vbmeta.img -----> START_OFFSET[$i] = ${START_OFFSET[$i]}"
+           dd if=$TMP_DIR/corrupted_${LIST_VBMETA_IMGS[$i]} bs=${START_OFFSET[$i]} conv=notrunc seek=1 of=$IMG_DIR/vbmeta_corrupted_${LIST_VBMETA_IMGS[$i]}
+        else
+           # create vendor_corrupted_verity.img for vendor.img
+           echo "Creating vendor_corrupted_${LIST_VBMETA_IMGS[$i]}..."
+           cp $TMP_DIR/$IMG.img $IMG_DIR/vendor_corrupted_${LIST_VBMETA_IMGS[$i]}
+           # echo "for vendor.img -----> START_OFFSET[$i] = ${START_OFFSET[$i]}"
+           dd if=$TMP_DIR/corrupted_${LIST_VBMETA_IMGS[$i]} bs=${START_OFFSET[$i]} conv=notrunc seek=1 of=$IMG_DIR/vendor_corrupted_${LIST_VBMETA_IMGS[$i]}
+        fi
+    done
+
+    # corrupt android.hardware.wifi@1.0-service binary
+    echo "Corrupting android.hardware.wifi@1.0-service binary..."
+    strings $TMP_DIR/$IMG.img | grep -m 1 "Wifi Hal is booting up" &>/dev/null
+    if [ $? -ne 0 ]
+    then
+        echo "'Wifi Hal is booting up' cannot be found in $TMP_DIR/$IMG.img, please find an other string to modify..."
+        exit 1
+    fi
+    cp $TMP_DIR/$IMG.img $IMG_DIR/vendor_corrupted_block.img
+    sed -i 's/Wifi Hal is booting up/booting up Wifi Hal is/' $IMG_DIR/vendor_corrupted_block.img
+}
+
 function generate_corrupted_boot_images {
     TMP_BOOT_IMG="$TMP_DIR/tmp.img"
 
@@ -204,7 +310,7 @@ function generate_corrupted_boot_images {
     fi
 }
 
-while getopts "b:chs:" opt; do
+while getopts "b:chs:v:" opt; do
     case $opt in
         h)
             usage
@@ -246,6 +352,27 @@ while getopts "b:chs:" opt; do
             echo "Copying $VBMETA_NAME..."
             cp $VBMETA_NAME $TMP_DIR/
             ;;
+        v)
+            IMG="vendor"
+            size=$(du -BM $OPTARG | awk '{print $1}')
+            echo "Warning, this operation will consume 4 * $size on your disk"
+            echo "Would you like to continue? [y/N]"
+            read v
+            case "$v" in
+                "y" | "Y" | "yes")
+                    ;;
+                *)
+                    echo "Aborted!"
+                    exit 1
+                    ;;
+            esac
+            echo "Copying $OPTARG..."
+            create_dir $TMP_DIR
+            cp $OPTARG $TMP_DIR/$IMG.img
+            VBMETA_NAME=`echo $OPTARG | sed 's/vendor/vbmeta/'`
+            echo "Copying $VBMETA_NAME..."
+            cp $VBMETA_NAME $TMP_DIR/
+            ;;
         c)
             echo "Cleaning $TMP_DIR, $IMG_DIR, $KEYS_DIR..."
             rm -rf $TMP_DIR
@@ -279,6 +406,9 @@ create_dir $IMG_DIR
 if [ "$IMG" = "system" ]
 then
     generate_corrupted_system_images
+elif [ "$IMG" = "vendor" ]
+then
+    generate_corrupted_vendor_images
 else
     create_dir $KEYS_DIR
     generate_user_keys
